CREATE TABLE usuario
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID,
    nome VARCHAR(255),
    email VARCHAR(255),
    dob date,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

